# Generated by Django 6.0b1 on 2026-03-18 17:49

import core.functions
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                (
                    'thumbnail',
                    models.ImageField(
                        blank=True,
                        max_length=500,
                        null=True,
                        upload_to=core.functions.user_thumbnails_path,
                    ),
                ),
                ('duration_seconds', models.PositiveBigIntegerField()),
                ('views_count', models.PositiveBigIntegerField(default=0)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('processing', 'Processing'),
                            ('public', 'Public'),
                            ('private', 'Private'),
                            ('unlisted', 'Unlisted'),
                            ('blocked', 'Blocked'),
                        ],
                        default='processing',
                        max_length=20,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='videos',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'db_table': 'videos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoFiles',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('resolution', models.CharField(max_length=10)),
                (
                    'video_format',
                    models.CharField(
                        choices=[
                            ('mp4', 'MP4'),
                            ('hls', 'HLS'),
                            ('dash', 'DASH'),
                        ],
                        default='mp4',
                        max_length=10,
                    ),
                ),
                (
                    'storage_url',
                    models.FileField(
                        max_length=500,
                        upload_to=core.functions.user_videos_path,
                    ),
                ),
                (
                    'video',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='files',
                        to='videos.videos',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Video file',
                'verbose_name_plural': 'Video files',
                'db_table': 'video_files',
            },
        ),
        migrations.AddIndex(
            model_name='videos',
            index=models.Index(
                fields=['user_id', '-created_at'],
                name='videos_user_id_5f9058_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='videos',
            index=models.Index(
                fields=['-views_count'], name='videos_views_c_adf589_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='videos',
            index=models.Index(
                fields=['status', '-created_at'],
                name='videos_status_3f96a7_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='videofiles',
            index=models.Index(
                fields=['video_id', 'resolution'],
                name='video_files_video_i_bdca15_idx',
            ),
        ),
    ]
