# Generated by Django 6.0b1 on 2026-03-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofiles',
            name='resolution',
            field=models.CharField(
                choices=[
                    ('1080', '1080px'),
                    ('720', '720px'),
                    ('480', '480px'),
                    ('360', '360px'),
                    ('144', '144px'),
                ],
                max_length=10,
            ),
        ),
    ]
