# Generated by Django 6.0b1 on 2026-04-18 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_initial'),
        ('videos', '0002_alter_videofiles_resolution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('content', models.TextField()),
                ('likes_count', models.PositiveIntegerField(default=0)),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'parent',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='replies',
                        to='actions.comment',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='comments',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'video',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='comments',
                        to='videos.videos',
                    ),
                ),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(
                        fields=['video_id', '-created_at'],
                        name='comments_video_i_adb6dd_idx',
                    ),
                    models.Index(
                        fields=['parent_id'],
                        name='comments_parent__9f8798_idx',
                    ),
                ],
            },
        ),
    ]
