# Generated by Django 6.0b1 on 2026-04-18 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes_count',
        ),
    ]
